export enum sagaTypes {
  STREAM_AUTH_STATECHANGE = 'STREAM_AUTH_STATECHANGE',
  STREAM_AUTH_STATECHANGE_CANCEL = 'STREAM_AUTH_STATECHANGE_CANCEL',

  STREAM_SIGNALS = 'STREAM_SIGNALS',
  STREAM_SIGNALS_CANCEL = 'STREAM_SIGNALS_CANCEL',

  STREAM_ANNOUNCEMENTS = 'STREAM_ANNOUNCEMENTS',
  STREAM_ANNOUNCEMENTS_CANCEL = 'STREAM_ANNOUNCEMENTS_CANCEL',

  STREAM_USERS = 'STREAM_USERS',
  STREAM_USERS_CANCEL = 'STREAM_USERS_CANCEL'
}
